const EVENTS = [

  // ── SPORTS ──────────────────────────────────────────────────
  {id:'box-cricket',cat:'sports',catLabel:'Sports',icon:'🏏',name:'Box Cricket',
   img:'https://i.ibb.co/jPp6c3k9/Box-Cricket.jpg',
   tagline:'Action-packed box cricket at Vyom \'26! Form your squad of 8 (5 Boys + 3 Girls) and compete for glory.',
   desc:'🏏 Vyom \'26 Box Cricket Competition\n\nGet ready to hit the ground running at the Vyom \'26 Box Cricket Competition! Lace up your shoes, grab your bat, and join us for an action-packed day of thrilling box cricket matches.\n\n📋 Team Composition:\n• Each team consists of 8 players — 5 Boys + 3 Girls\n• One player can play for only one team\n• Each team can have a maximum of 3 players who have represented the University/College team\n• Proper sportswear mandatory (Shoes, T-Shirt, Lower)\n\n🏟️ Playing Area:\n• Box cricket is played in a confined space, not in the actual cricket field\n• First over compulsorily bowled by a girl\n• Full arm bowling is compulsory for boys\n• Matches are typically played with 4 overs per innings\n\n⚖️ Umpire\'s call is final. Good sportsmanship is expected at all times.',
   date:'March 26–28, 2026',venue:'Staff Parking Area',team:'8 Members (5 Boys + 3 Girls)',
   contacts:[['Aditya Raj','9234578690'],['Nilmani Singh','7563016593'],['Raunit Kumar','6299240873']],
   formFields:[
     {id:'teamName',label:'Team Name',type:'text',placeholder:'e.g. Thunder XI',required:true,full:true},
     {id:'name',label:'Team Captain Name',type:'text',placeholder:'e.g. Arjun Sharma',required:true},
     {id:'erpId',label:'ERP ID (Captain)',type:'text',placeholder:'e.g. 2210101234',required:true},
     {id:'branch',label:'Branch (Captain)',type:'text',placeholder:'e.g. CSE 3rd Year',required:true},
     {id:'college',label:'College (Captain)',type:'select',options:['RISU-SOCSE','RISU-SOIT','RISU-SOP','RISU-SOLS','RISU-SOET','RISU-SOMC','RCET','GDRCST','RIPER/RCPSR'],required:true},
     {id:'phone',label:'Contact Info (Captain)',type:'tel',placeholder:'10-digit mobile',required:true},
     {id:'email',label:'Email Address (Captain)',type:'email',placeholder:'captain@email.com',required:true},
     {id:'member1',label:'Team Member 1',type:'text',placeholder:'Full name',required:true},
     {id:'erp1',label:'ERP (Member 1)',type:'text',placeholder:'ERP ID',required:true},
     {id:'college1',label:'College (Member 1)',type:'select',options:['RISU-SOCSE','RISU-SOIT','RISU-SOP','RISU-SOLS','RISU-SOET','RISU-SOMC','RCET','GDRCST','RIPER/RCPSR'],required:true},
     {id:'contact1',label:'Contact Info (Member 1)',type:'tel',placeholder:'10-digit mobile',required:true},
     {id:'member2',label:'Team Member 2',type:'text',placeholder:'Full name',required:true},
     {id:'erp2',label:'ERP (Member 2)',type:'text',placeholder:'ERP ID',required:true},
     {id:'college2',label:'College (Member 2)',type:'select',options:['RISU-SOCSE','RISU-SOIT','RISU-SOP','RISU-SOLS','RISU-SOET','RISU-SOMC','RCET','GDRCST','RIPER/RCPSR'],required:true},
     {id:'contact2',label:'Contact Info (Member 2)',type:'tel',placeholder:'10-digit mobile',required:true},
     {id:'member3',label:'Team Member 3',type:'text',placeholder:'Full name',required:true},
     {id:'erp3',label:'ERP (Member 3)',type:'text',placeholder:'ERP ID',required:true},
     {id:'college3',label:'College (Member 3)',type:'select',options:['RISU-SOCSE','RISU-SOIT','RISU-SOP','RISU-SOLS','RISU-SOET','RISU-SOMC','RCET','GDRCST','RIPER/RCPSR'],required:true},
     {id:'contact3',label:'Contact Info (Member 3)',type:'tel',placeholder:'10-digit mobile',required:true},
     {id:'member4',label:'Team Member 4',type:'text',placeholder:'Full name',required:true},
     {id:'erp4',label:'ERP (Member 4)',type:'text',placeholder:'ERP ID',required:true},
     {id:'college4',label:'College (Member 4)',type:'select',options:['RISU-SOCSE','RISU-SOIT','RISU-SOP','RISU-SOLS','RISU-SOET','RISU-SOMC','RCET','GDRCST','RIPER/RCPSR'],required:true},
     {id:'contact4',label:'Contact Info (Member 4)',type:'tel',placeholder:'10-digit mobile',required:true},
     {id:'member5',label:'Team Member 5',type:'text',placeholder:'Full name',required:true},
     {id:'erp5',label:'ERP (Member 5)',type:'text',placeholder:'ERP ID',required:true},
     {id:'college5',label:'College (Member 5)',type:'select',options:['RISU-SOCSE','RISU-SOIT','RISU-SOP','RISU-SOLS','RISU-SOET','RISU-SOMC','RCET','GDRCST','RIPER/RCPSR'],required:true},
     {id:'contact5',label:'Contact Info (Member 5)',type:'tel',placeholder:'10-digit mobile',required:true},
     {id:'member6',label:'Team Member 6',type:'text',placeholder:'Full name',required:true},
     {id:'erp6',label:'ERP (Member 6)',type:'text',placeholder:'ERP ID',required:true},
     {id:'college6',label:'College (Member 6)',type:'select',options:['RISU-SOCSE','RISU-SOIT','RISU-SOP','RISU-SOLS','RISU-SOET','RISU-SOMC','RCET','GDRCST','RIPER/RCPSR'],required:true},
     {id:'contact6',label:'Contact Info (Member 6)',type:'tel',placeholder:'10-digit mobile',required:true},
     {id:'member7',label:'Team Member 7',type:'text',placeholder:'Full name',required:true},
     {id:'erp7',label:'ERP (Member 7)',type:'text',placeholder:'ERP ID',required:true},
     {id:'college7',label:'College (Member 7)',type:'select',options:['RISU-SOCSE','RISU-SOIT','RISU-SOP','RISU-SOLS','RISU-SOET','RISU-SOMC','RCET','GDRCST','RIPER/RCPSR'],required:true},
     {id:'contact7',label:'Contact Info (Member 7)',type:'tel',placeholder:'10-digit mobile',required:true,full:true},
   ]},

  {id:'carrom',cat:'sports',catLabel:'Sports',icon:'🎯',name:'Carrom',
   img:'https://i.ibb.co/8QLMhXT/Carrom.jpg',
   tagline:'Test your precision and strategy at the Carrom Tournament — Vyom \'26!',
   desc:'🎯 Vyom \'26 Carrom Tournament\n\nTest your precision, flicking skills, and board sense! Compete in an exciting individual battle of strategy and accuracy.\n\nPlayers will compete in a round-robin format followed by knockout rounds. May the best striker win!\n\nVenue: TC-05\nFormat: Single Player',
   date:'March 26–28, 2026',venue:'TC-05',team:'Single Player',
   contacts:[['Aditi Sahu','9981990218'],['Raja Kumar','9504836138']],
   formLink:'https://docs.google.com/forms/d/1cKFP9OADtBqKa9tn0PHkqHl6O41XBXF407ozasR3-b8/edit?ts=69c01e58'},

  {id:'chess',cat:'sports',catLabel:'Sports',icon:'♟️',name:'Chess',
   img:'https://i.ibb.co/S70C56M5/Chess.jpg',
   tagline:'The ultimate battle of wits at Vyom \'26! Prove you are the grandmaster.',
   desc:'♟️ Vyom \'26 Chess Championship\n\nShowcase your intellect, foresight, and strategic thinking. Compete against the best minds from across the campus.\n\nStandard time controls apply. Swiss format with knockout finals for top performers.\n\nVenue: TC-02\nFormat: Single Player',
   date:'March 26–28, 2026',venue:'TC-02',team:'Single Player',
   contacts:[['Vipul Kumar Sahil','7632013805'],['Vishwajeet Upadhyay','8603077674']],
   formLink:'https://forms.gle/fLZzigMyKyTm1ppp8'},

  {id:'volleyball',cat:'sports',catLabel:'Sports',icon:'🏐',name:'Volleyball',
   img:'https://i.ibb.co/Wp0S0dvx/Volleyball.jpg',
   tagline:'High-energy volleyball at Vyom \'26! Spike, block, and dive your way to glory.',
   desc:'🏐 Vyom \'26 Volleyball Tournament!\n\nSpike, block, and dive your way to glory. Both Boys and Girls teams are welcome to participate!\n\nKnockout format. Standard 6-player team rules apply. Best of 3 sets per match.\n\nVenue: Volleyball Court',
   date:'March 26–28, 2026',venue:'Volleyball Court',team:'Boys & Girls Teams',
   contacts:[['Prem Raj','7541921135'],['Vivek Singh','9608992114']],
   formLink:'https://docs.google.com/forms/u/2/d/1h_7-8QcQAp0T48IrarQvR86g97hn7cF8DNsSooefY-E/edit?usp=sharing_eil_se_dm&ts=69bfb6e1'},

  {id:'basketball',cat:'sports',catLabel:'Sports',icon:'🏀',name:'Basketball',
   img:'https://i.ibb.co/M5M1tWhb/Basketball.jpg',
   tagline:'Dribble, shoot and score at Vyom \'26! Inter-college and Intra-college formats.',
   desc:'🏀 Vyom \'26 Basketball Championship!\n\nTwo formats — Inter-college and Intra-college, for both Boys and Girls. Dominate the court, run the plays and bring home the trophy!\n\nVenue: Basketball Court',
   date:'March 25–27, 2026',venue:'Basketball Court',team:'Boys & Girls Teams',
   contacts:[['Saurabh Raj','6200389016'],['Navneet','8102366979']],
   formLink:'https://forms.gle/LMUz1knbS6eTkCts5'},

  {id:'kabaddi',cat:'sports',catLabel:'Sports',icon:'🤼',name:'Kabaddi',
   img:'https://i.ibb.co/yFW6508H/kabaddi.jpg',
   tagline:'Strength, agility and breath control — Kabaddi at Vyom \'26!',
   desc:'🤼 Vyom \'26 Kabaddi Tournament\n\nAssemble your team and prove dominance on the mat! Touch, hold, escape — the oldest Indian sport returns.\n\nStandard Kabaddi rules apply. Knockout format. Held across multiple rounds.\n\nVenue: Beside Basketball Court',
   date:'March 26–28, 2026',venue:'Beside Basketball Court',team:'Standard Team',
   contacts:[['Rohit Raj','9523396888'],['Prashant Kumar','9470668237']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSe3GOAUJbGGSrUKAO6WFGYpNVSfxNiG0izjmM_AJdv1Gju_vg/viewform'},

  {id:'kho-kho',cat:'sports',catLabel:'Sports',icon:'🏃',name:'Kho Kho',
   img:'https://i.ibb.co/Zp8KxpRR/kho-kho.jpg',
   tagline:'Speed and strategy in the classic Kho Kho at Vyom \'26!',
   desc:'🏃 Vyom \'26 Kho Kho Championship\n\nFast-paced traditional sport requiring lightning reflexes, teamwork, speed, and strategy. One of India\'s most exciting indigenous sports.\n\nStandard Kho Kho rules apply. Knockout format.\n\nVenue: Beside Basketball Court',
   date:'March 26–28, 2026',venue:'Beside Basketball Court',team:'Standard Team',
   contacts:[['Kaushik Sinha','9135447701'],['Vaishnavi Kumari','6206697573']],
   formLink:'https://docs.google.com/forms/d/18aijTV3V63y2c8EH3H2C2l10nWNeGlnM8CLG4_MCiF4/edit?usp=sharing_eil_se_dm&ts=69c00460'},

  {id:'athletics',cat:'sports',catLabel:'Sports',icon:'🏃',name:'Athletics',
   img:'https://i.ibb.co/bMjS1svV/Athletics-100-M.jpg',
   tagline:'Speed, stamina and strength — Athletics at Vyom \'26!',
   desc:'🏃 Vyom \'26 Athletics\n\nMultiple track and field events — 100m Sprint (Boys & Girls), 100m×4 Relay Race, Flat Race, Discus Throw, Shot Put Throw, and more.\n\nSeparate categories for Boys and Girls. Multiple heats with top athletes advancing to finals.\n\nVenue: Ground',
   date:'March 26–28, 2026',venue:'Ground',team:'Individual / Team',
   contacts:[['Ayush Patel','8709114134'],['Abhishek Kumar','6299929022']],
   formLink:'https://docs.google.com/forms/d/16xMqPdH85Fqfcg5DO8bLjhGKd2pc95zV4VNAyXybXsM/viewform?edit_requested=true'},

  {id:'arm-wrestling',cat:'sports',catLabel:'Sports',icon:'💪',name:'Arm Wrestling',
   img:'https://i.ibb.co/3mgzFC4Y/Arm-Wrestling.jpg',
   tagline:'Pure strength on the table — Arm Wrestling at Vyom \'26!',
   desc:'💪 Vyom \'26 Arm Wrestling Championship\n\nOne-on-one battles of pure power and technique. Open to all! Compete across weight categories and prove you have the strongest grip on campus.\n\nWeight categories ensure fair competition. Knockout bracket format.\n\nVenue: B Block Entrance',
   date:'March 26–28, 2026',venue:'B Block Entrance',team:'Single Player',
   contacts:[['Shivam Raj','9006663697']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSetpKvp3IhvvbEuMzZL4vHqtF8R7EjnWDoTifzRxhurMmwurg/viewform'},

  {id:'table-tennis',cat:'sports',catLabel:'Sports',icon:'🏓',name:'Table Tennis',
   img:'https://i.ibb.co/m5HP4Vrf/Table-Tennis.jpg',
   tagline:'Precision, reflexes and spin — Table Tennis at Vyom \'26!',
   desc:'🏓 Vyom \'26 Table Tennis Tournament\n\nSingle player format. Lightning-fast rallies, killer spin, and match-winning precision.\n\nStandard TT rules. Knockout format.\n\nVenue: TC-05',
   date:'March 26–28, 2026',venue:'TC-05',team:'Single Player',
   contacts:[['Shivam Raj','9470840228'],['Sagar Bharti','7987504890']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSe_tpmod82a7zxPSWWMiH7GxAfqF3CiZamS4KmGKQSZJG-NCw/viewform'},

  {id:'badminton',cat:'sports',catLabel:'Sports',icon:'🏸',name:'Badminton',
   img:'https://i.ibb.co/rfwVCrzM/Badminton.jpg',
   tagline:'Fast rallies and smashing winners — Badminton at Vyom \'26!',
   desc:'🏸 Vyom \'26 Badminton Tournament\n\nFast-paced singles competition for Boys and Girls. Showcase your footwork, smashes and drop shots to advance through the rounds.\n\nStandard badminton rules (21 points per game). Knockout format.\n\nVenue: Boys Hostel & Girls Hostel',
   date:'March 26–28, 2026',venue:'Boys Hostel & Girls Hostel',team:'Single Player',
   contacts:[['Azad Agrawal','7750081487'],['Abhay Raj','6203013422']],
   formLink:'https://docs.google.com/forms/d/1It5BRuRA74QlICaYqvGwLf7FMp8sw8KyRiWPqt1aILo/edit?ts=69c01d4f'},

  {id:'ball-dribbling',cat:'sports',catLabel:'Sports',icon:'⚽',name:'Ball Dribbling',
   img:'',
   tagline:'Showcase your footwork and ball control at Vyom \'26 Ball Dribbling!',
   desc:'⚽ Vyom \'26 Ball Dribbling Challenge\n\nTest your agility, control, and speed through a timed dribbling obstacle course. Show your ball mastery!\n\nIndividual timed format. Multiple heats with top performers advancing.\n\nVenue: Basketball Court',
   date:'March 26–28, 2026',venue:'Basketball Court',team:'Individual',
   contacts:[],
   formLink:'https://docs.google.com/forms/d/1dV0kAt71MWuKvInNRAu_g1pECOCfvXfUjasPimA1o84/edit?ts=69c251da'},

  {id:'sack-race',cat:'sports',catLabel:'Sports',icon:'🥇',name:'Sack Race',
   img:'',
   tagline:'Hop your way to glory at Vyom \'26 Sack Race!',
   desc:'🥇 Vyom \'26 Sack Race\n\nA classic fun sport where competitors hop inside a sack from start to finish. Coordination, balance, and speed — all rolled into one hilarious event!\n\nIndividual format. Multiple heats. Fastest hops win.\n\nVenue: Ground',
   date:'March 26–28, 2026',venue:'Ground',team:'Individual',
   contacts:[['Sonu Kumar','9508906992'],['Pratyush Pankaj','9798280702']],
   formLink:''},

  // ── E-SPORTS ──
  {id:'bgmi',cat:'esports',catLabel:'E-Sports',icon:'🎮',name:'BGMI',
   img:'https://i.ibb.co/k2JF1wGv/BGMI.jpg',
   tagline:'Battle royale at Vyom \'26! Land smart, fight hard — only one squad survives.',
   desc:'🎮 Vyom \'26 BGMI Tournament\n\nBring your own device. Form your squad, choose your drop zone strategically, and eliminate every rival squad. Classic Battle Royale format.\n\nSquad of 4. BYOD. Standard tournament settings apply. Multiple rounds — Qualifiers, Semi Finals & Finals.\n\nVenue: SA7',
   date:'March 26–28, 2026',venue:'SA7',team:'Squad of 4 (BYOD)',
   contacts:[['Shikha Tomar','9770490724'],['Harshit Sinha','9301826487']],
   formLink:'https://forms.gle/BqfTgyfcwFTSdH4S7'},

  {id:'valorant',cat:'esports',catLabel:'E-Sports',icon:'🎯',name:'Valorant',
   img:'https://i.ibb.co/tM0VDw9h/Valorant.jpg',
   tagline:'Tactical shooter skills at Vyom \'26 Valorant! Aim, ability, win.',
   desc:'🎯 Vyom \'26 Valorant Tournament\n\nBring your own device. The best tactical minds will rise through the bracket.\n\nTeam of 5. BYOD. Standard Valorant competitive settings.\n\nVenue: SA1',
   date:'March 26–28, 2026',venue:'SA1',team:'Team of 5 (BYOD)',
   contacts:[['Arjav Jain','8319337033'],['Shweta Yadav','9424282146']],
   formLink:'https://forms.gle/ig635jaPZEcW6ECfA'},

  {id:'free-fire',cat:'esports',catLabel:'E-Sports',icon:'🔥',name:'Free Fire',
   img:'https://i.ibb.co/JFSCTWC7/Free-fire.jpg',
   tagline:'Last squad standing at Vyom \'26 Free Fire! Battle royale on mobile.',
   desc:'🔥 Vyom \'26 Free Fire Tournament\n\nForm a squad of 4. Last squad standing takes it all! Classic Battle Royale mode on mobile.\n\nBYOD. Squad of 4. Standard Free Fire tournament rules apply.\n\nVenue: SA2, SA3, SA4, SA5, SA6',
   date:'March 26–28, 2026',venue:'SA2, SA3, SA4, SA5, SA6',team:'Squad of 4 (BYOD)',
   contacts:[['Sumit Kumar','9229923377'],['Kuldeep Dhruw','9243330528']],
   formLink:'https://forms.gle/44Bm66BfmrZdNGMs7'},

  {id:'cod-mobile',cat:'esports',catLabel:'E-Sports',icon:'🔫',name:'Call of Duty Mobile',
   img:'https://i.ibb.co/NntjsW3t/Call-Of-duty.jpg',
   tagline:'Modern warfare on mobile at Vyom \'26 COD Mobile!',
   desc:'🔫 Vyom \'26 Call of Duty Mobile Tournament\n\nThe most iconic FPS franchise goes mobile. Form your squad, pick your loadouts, and dominate every game mode.\n\nTeam of 5. BYOD. Standard CODM tournament settings.\n\nVenue: SA08',
   date:'March 26–28, 2026',venue:'SA08',team:'Team of 5 (BYOD)',
   contacts:[['Alok Kumar','6201900278'],['Ramakant Dhruw','7725019318']],
   formLink:'https://forms.gle/sh66ytxPk4BoTzQ99'},

  {id:'stumble-guys',cat:'esports',catLabel:'E-Sports',icon:'🎪',name:'Stumble Guys',
   img:'https://i.ibb.co/d4f7tyMD/Stumble.jpg',
   tagline:'Chaotic fun and last-player-standing at Vyom \'26 Stumble Guys!',
   desc:'🎪 Vyom \'26 Stumble Guys Tournament\n\nThe wildest party game on mobile! Navigate obstacle courses, survive elimination rounds, and be the last one standing.\n\nSolo format. BYOD. Multiple rounds.\n\nVenue: SA16',
   date:'March 26–28, 2026',venue:'SA16',team:'Single Player (BYOD)',
   contacts:[['Raunak Jaiswal','9244127497']],
   formLink:'https://forms.gle/38ice1jhmBa7JGyz7'},

  {id:'strike-world',cat:'esports',catLabel:'E-Sports',icon:'⚔️',name:'Strike World',
   img:'https://i.ibb.co/tp05XtfH/Strike-world.jpg',
   tagline:'Tactical combat gaming at Vyom \'26 — Strike World! Show your skills and dominate.',
   desc:'⚔️ Vyom \'26 Strike World Tournament\n\nStep into intense tactical gaming combat. Show your strategy, reflexes, and teamwork to outlast every opponent.\n\nBYOD. Standard tournament rules apply. Multiple rounds.\n\nVenue: Stalls',
   date:'March 26–28, 2026',venue:'Stalls',team:'Team (BYOD)',
   contacts:[],
   formLink:'https://forms.gle/MaWutx1ir8sboWMaA'},

  {id:'esports-chess',cat:'esports',catLabel:'E-Sports',icon:'♟️',name:'Chess (E-Sports)',
   img:'https://i.ibb.co/PsKTyvG5/Chess-com.jpg',
   tagline:'Digital chess showdown at Vyom \'26 — compete online and prove your genius!',
   desc:'♟️ Vyom \'26 Chess — E-Sports Edition\n\nOnline chess competition on a digital platform. Compete in rapid or blitz format against opponents from across campus.\n\nIndividual. BYOD. Standard chess tournament rules online.\n\nVenue: Stalls',
   date:'March 26–28, 2026',venue:'Stalls',team:'Individual (BYOD)',
   contacts:[],
   formLink:'https://forms.gle/DnLMZ9egSAhhyw997'},

  // ── TECHNICAL ──
  {id:'mvp-in-a-day',cat:'technical',catLabel:'Technical',icon:'🚀',name:'MVP Building (MSA)',
   img:'https://i.ibb.co/GfXS7Rrb/Mvp-buidling.jpg',
   tagline:'Ship a minimum viable product in one day at Vyom \'26 — MSA Event!',
   desc:'🚀 Vyom \'26 — MVP Building (Microsoft Student Ambassadors)\n\nDesign, build and present a Minimum Viable Product within a single day. Use any technology — Azure, web, AI, mobile.\n\nSponsored by Microsoft Learn Student Ambassadors. Team of 1–4.\n\nVenue: GA20 Microsoft Lab\nTime: 9 AM to 12 PM',
   date:'March 28, 2026 — 9 AM to 12 PM',venue:'GA20 Microsoft Lab',team:'1–4 Members',
   contacts:[['Rishi Soni','9296161262'],['Akshat Sahu','9303937565']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSc_kPUSj-pmUlSIfXbOlH5zzLEb-ayvDfQvHxscLkIOgUbu8A/viewform?usp=publish-editor'},

  {id:'prompt-arena',cat:'technical',catLabel:'Technical',icon:'🤖',name:'Prompt Arena (GFG)',
   img:'https://i.ibb.co/Mkz71QNp/prompt-arena.jpg',
   tagline:'Master AI prompting and win at Vyom \'26 Prompt Arena — GFG!',
   desc:'🤖 Vyom \'26 — Prompt Arena (GeeksForGeeks)\n\nThe age of AI is here. Craft the perfect prompts to solve real-world problems using LLMs and generative AI tools.\n\nOrganised by GeeksForGeeks. Individual. Multiple rounds.\n\nVenue: SA17\nTime: 9 AM to 12 PM',
   date:'March 26, 2026 — 9 AM to 12 PM',venue:'SA17',team:'Individual',
   contacts:[['Ashish Raj','9102362667'],['Kumar Divyanshu','8002087006']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSdPJOFcTXeS76sDHXuvQv71ybQR-7c-WYavH-lRHv4Q5fju8A/viewform?usp=publish-editor'},

  {id:'kiro-quest',cat:'technical',catLabel:'Technical',icon:'☁️',name:'Kiro Quest (AWS)',
   img:'https://i.ibb.co/dswDbWFq/75.jpg',
   tagline:'Cloud-powered problem solving at Vyom \'26 — AWS Kiro Quest!',
   desc:'☁️ Vyom \'26 — Kiro Quest (Amazon Web Services)\n\nA cloud-focused technical challenge powered by AWS. Solve problems using AWS services.\n\nOrganised by AWS community. Individual or team of 2.\n\nVenue: SA18\nTime: 1 PM to 4 PM',
   date:'March 26, 2026 — 1 PM to 4 PM',venue:'SA18',team:'1–2 Members',
   contacts:[['Abhishek Yadav','9340900774'],['Aditya Mohan','6206013946']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSeAIERv1fJS_kAIgL8YijZ5qrm0AoI5t2TvnAIo7ca1D-wJxg/viewform?usp=publish-editor'},

  {id:'google-hackathon',cat:'technical',catLabel:'Technical',icon:'🖥️',name:'Google Hackathon',
   img:'https://i.ibb.co/sTCxmSC/Google-hackathon.jpg',
   tagline:'Build, innovate and present at the Google Hackathon — Vyom \'26!',
   desc:'🖥️ Vyom \'26 Google Hackathon\n\nThe flagship hackathon of VYOM 2026! Build real solutions using Google technologies — Flutter, TensorFlow, Cloud Platform.\n\nTeam of 2–4. Any tech stack accepted. Google tools preferred.\n\nVenue: FA14, FA16, FA17, FA21, FA15 (backup)\nTime: 8 AM to 11 AM',
   date:'March 27, 2026 — 8 AM to 11 AM',venue:'FA14, FA16, FA17, FA21',team:'2–4 Members',
   contacts:[['Ronit Shekhar','7857838745']],
   formLink:'https://www.geeksforgeeks.org/hack-a-thon/digital-campus-on-google-cloud-hack-sprint-rungta-international-skills-university'},

  // ── ENTREPRENEURSHIP (RUBI) ──
  {id:'shark-tank',cat:'entrepreneurship',catLabel:'E-Summit',icon:'🦈',name:'Shark Tank 2.0',
   img:'',
   tagline:'Pitch your startup idea to investors and win big at Vyom \'26 Shark Tank 2.0!',
   desc:'🦈 Vyom \'26 — Shark Tank 2.0 (RUBI)\n\nStep into the tank and pitch your startup idea to a panel of sharks — investors, industry experts, and alumni.\n\nIndividual or team. Prepared pitches. Judged on idea viability, pitch quality, financials, and Q&A.\n\nVenue: B Block Auditorium',
   date:'March 25, 2026',venue:'B Block Auditorium',team:'Individual / Team',
   contacts:[['Ayush Wankhade','9238922791'],['Kshitij Patel','9302306666']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSdkqgqPnnE-7Apjd2DllLcvDJEpQBHEFyTvs3yh7t6CFoQEUA/viewform?usp=publish-editor'},

 

  // ── CULTURAL (RANGMANCH) ──
  {id:'solo-dance',cat:'cultural',catLabel:'Cultural',icon:'💃',name:'Solo Dance',
   img:'https://i.ibb.co/RTXdykCm/solo-dance.jpg',
   tagline:'Own the stage at Vyom \'26 Solo Dance — any style, your moment!',
   desc:'💃 Vyom \'26 Solo Dance Competition\n\nAny dance style welcome — classical, hip-hop, freestyle, folk, contemporary, Bollywood. This is your moment to own the stage.\n\nJudged on technique, expression, stage presence and choreography. Performance duration: 3–5 minutes.\n\nVenue: B Block Open Stage',
   date:'March 26–28, 2026',venue:'B Block Open Stage',team:'Single Player',
   contacts:[['Sujal Bisen','7724964624'],['Sakshi Yadav','9244503604']],
   formLink:'https://docs.google.com/forms/u/2/d/1qh1Yfo5ZWuKj5z55tudjn-nvfpgjpfayo20wOxs4apo/edit?usp=sharing_eil_se_dm&ts=69c0d11b'},

  {id:'group-dance',cat:'cultural',catLabel:'Cultural',icon:'👯',name:'Group Dance',
   img:'https://i.ibb.co/GQm61Q9V/group-dance.jpg',
   tagline:'Synchronize and shine at Vyom \'26 Group Dance — 3 to 7 members on stage!',
   desc:'👯 Vyom \'26 Group Dance Competition\n\nMin 3, max 7 members. Any style welcome — fusion, Bollywood, folk, contemporary.\n\nJudged on choreography, synchronization, energy and stage presence. Duration: 4–7 minutes.\n\nVenue: B Block Open Stage',
   date:'March 26–28, 2026',venue:'B Block Open Stage',team:'3–7 Members',
   contacts:[['Rudra Prakash Sahu','7646934846'],['Manas Dhruw','9098356760']],
   formLink:'https://docs.google.com/forms/u/2/d/1odRtGAVtjW8k5ySUExHIdrVceet_Z1my44U1I4pGMR8/edit?usp=sharing_eil_se_dm&ts=69c0d198'},

  {id:'solo-singing',cat:'cultural',catLabel:'Cultural',icon:'🎤',name:'Solo Singing',
   img:'https://i.ibb.co/fG4D8GKd/solo-sing.jpg',
   tagline:'Showcase your voice at Vyom \'26 Solo Singing — Bollywood, classical, pop and more!',
   desc:'🎤 Vyom \'26 Solo Singing Competition\n\nAny genre welcome — Bollywood, classical, pop, western, Indie. Let your voice carry the stage.\n\nJudged on vocals, pitch, expression and stage presence. Duration: 3–4 minutes. Karaoke/backing track allowed.\n\nVenue: B Block Open Stage',
   date:'March 26–28, 2026',venue:'B Block Open Stage',team:'Single Player',
   contacts:[['Arpit Mishra','9669689470'],['Md. Ayaz Qureshi','9302897064']],
   formLink:'https://docs.google.com/forms/u/2/d/1v12nVwFvZy3i9nVqx1JYGBzamXkHFg012lT4tQAwK_s/edit?usp=sharing_eil_se_dm&ts=69c0d15c'},

  {id:'group-singing',cat:'cultural',catLabel:'Cultural',icon:'🎶',name:'Group Singing',
   img:'https://i.ibb.co/nNQgF9rq/group-singing.jpg',
   tagline:'Harmonize together at Vyom \'26 Group Singing!',
   desc:'🎶 Vyom \'26 Group Singing Competition\n\nMin 2, max 5 members. Perfect harmony, tight arrangement, and collective expression wins the stage.\n\nJudged on harmony, vocals, arrangement and presentation. Duration: 4–5 minutes.\n\nVenue: B Block Open Stage',
   date:'March 26–28, 2026',venue:'B Block Open Stage',team:'2–5 Members',
   contacts:[['Md. Jeeshan','6266018657'],['Sara Fatima','7489285877']],
   formLink:'https://docs.google.com/forms/d/1uOs87t4tXmnlHWpG8o4QgChNykLAfxrT0AHcZpXDr40/edit?ts=69c101e3'},

  {id:'instrumental-solo',cat:'cultural',catLabel:'Cultural',icon:'🎸',name:'Instruments Competition (Solo)',
   img:'https://i.ibb.co/VpvYw95M/solo-instrumental.jpg',
   tagline:'Let your instrument speak at Vyom \'26 — Solo Instruments Competition!',
   desc:'🎸 Vyom \'26 Instruments Competition — Solo (RAG)\n\nAny instrument welcome — Guitar, Tabla, Flute, Violin, Keyboard, Sitar, Harmonium, Bansuri and more. Perform a solo piece and let your music do the talking.\n\nJudged on technique, rhythm, emotion and stage presence. Duration: 3–5 minutes.\n\nVenue: B Block Open Stage',
   date:'March 26–28, 2026',venue:'B Block Open Stage',team:'Solo',
   contacts:[['Ayush Raj Saini','8092286605'],['G. Pawan','6204202567']],
   formLink:'https://docs.google.com/forms/d/1Gq2q8IboB8DJ_n2-MLvDUg33ppbjuFgbEGGbx4AGcDI/edit?ts=69c1f4e2'},

  {id:'instrumental-group',cat:'cultural',catLabel:'Cultural',icon:'🥁',name:'Instruments Competition (Group)',
   img:'https://i.ibb.co/VpvYw95M/solo-instrumental.jpg',
   tagline:'Jam together and create magic at Vyom \'26 — Group Instruments Competition!',
   desc:'🥁 Vyom \'26 Instruments Competition — Group (RAG)\n\nBring your band! Any combination of instruments — rock, fusion, classical ensemble, folk band, jazz. Collaborate and create an unforgettable performance.\n\nMin 2, max 6 members. Any genre. Duration: 5–8 minutes.\n\nJudged on ensemble harmony, technique, arrangement, and stage presence.\n\nVenue: B Block Open Stage',
   date:'March 26–28, 2026',venue:'B Block Open Stage',team:'Group (2–6 Members)',
   contacts:[['Ayush Raj Saini','8092286605'],['G. Pawan','6204202567']],
   formLink:'https://docs.google.com/forms/d/1Gq2q8IboB8DJ_n2-MLvDUg33ppbjuFgbEGGbx4AGcDI/edit?ts=69c1f4e2'},

  {id:'dance-face-battle',cat:'cultural',catLabel:'Cultural',icon:'🕺',name:'Dance Face Battle',
   img:'https://i.ibb.co/whyZLkJ8/dance-face-battle.jpg',
   tagline:'Head-to-head freestyle — no prep, just vibes at Vyom \'26 Dance Face Battle!',
   desc:'🕺 Vyom \'26 Dance Face Battle (Intercollege)\n\nOn-the-spot freestyle. No prep needed. The crowd and judges decide. Open to all colleges.\n\nElimination format. Judged on creativity, energy, crowd response and improvisation.\n\nVenue: B Block Auditorium',
   date:'March 26, 2026',venue:'B Block Auditorium',team:'On-the-Spot Registration',
   contacts:[['Ayush Raj Saini','8092286605'],['Mahek Sahu','9301966778']],
   formLink:'https://docs.google.com/forms/u/2/d/1XztJ9hootoK2IvpyBJqJ8aRHW7lpcKM_Ln1DPbKjJfA/edit?usp=sharing_eil_se_dm&ts=69c0d17b'},

  {id:'skit-drama',cat:'cultural',catLabel:'Cultural',icon:'🎭',name:'Skit / Drama / Mime',
   img:'https://i.ibb.co/CpbVSs5Z/nukad-natak.jpg',
   tagline:'Tell powerful stories on stage — Skit, Drama & Mime at Vyom \'26!',
   desc:'🎭 Vyom \'26 Skit / Drama / Mime (Nukkad Natak)\n\nStreet theatre, full drama, or silent mime — any form of performing arts welcome.\n\nTeam of 3–15 members. Performance duration: 8–15 minutes. Any theme — social, comedy, drama, mime.\n\nVenue: B Block Open Stage',
   date:'March 26–28, 2026',venue:'B Block Open Stage',team:'3–15 Members',
   contacts:[['Abhishek Tiwari','9039301419'],['Krishna Rathor','8103792371']],
   formLink:'https://docs.google.com/forms/u/2/d/1NuW6jkrKIdPPQ53TprRbR74vcqYDiv3ZzRo0DB5RMck/edit?usp=sharing_eil_se_dm&ts=69c1f444'},

  {id:'mimicry',cat:'cultural',catLabel:'Cultural',icon:'🎙️',name:'Mimicry Competition',
   img:'https://i.ibb.co/xKt5cyDb/mimicry.jpg',
   tagline:'Imitate, entertain and win at Vyom \'26 Mimicry Competition!',
   desc:'🎙️ Vyom \'26 Mimicry Competition\n\nImpersonate celebrities, politicians, film characters, or anyone you like!\n\nIndividual. 3–5 minutes performance. Judged on accuracy, entertainment value and variety.\n\nVenue: B Block Open Stage',
   date:'March 26–28, 2026',venue:'B Block Open Stage',team:'Individual',
   contacts:[['Pushpendra Sahu','7000708835'],['Shruti Dubey','7440715100']],
   formLink:'https://docs.google.com/forms/d/1BwfCPcqGRMWrZI-3pGKmnlkFS1vJ-MK_E3zp2HijZ2o/edit?ts=69c1f527'},

  {id:'hair-styling',cat:'cultural',catLabel:'Cultural',icon:'✂️',name:'Hair Styling',
   img:'https://i.ibb.co/scyhkZ1/hair-styling-competition.jpg',
   tagline:'Style, creativity and flair — Hair Styling Competition at Vyom \'26 (Radiance)!',
   desc:'✂️ Vyom \'26 Hair Styling Competition (Radiance)\n\nShowcase your creative hair styling skills on a model. Themes can be inspired by culture, fantasy, fashion, or fusion.\n\nIndividual stylist working on a volunteer model. Judged on creativity, technique, and final look.\n\nVenue: A Block Waiting Area (next to Account Section)',
   date:'March 26–28, 2026',venue:'A Block Waiting Area (next to Account Section)',team:'Individual (Stylist)',
   contacts:[['Apeksha Thawkar','9373800686'],['Divya Sahu','9039345548']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSceO-BWz5R4r1MOt4LAvohwZx6uBZtV93aKlXyKqGQl75zahA/viewform'},

  // ── CREATIVE / ART (RAG) ──
  {id:'canvas-15min',cat:'creative',catLabel:'Creative',icon:'🎨',name:'15 Min Canvas',
   img:'https://i.ibb.co/qMBnCtqx/15-min-canvas.jpg',
   tagline:'Create a masterpiece in just 15 minutes at Vyom \'26!',
   desc:'🎨 Vyom \'26 — 15 Minute Canvas Challenge (RAG)\n\nThink fast, paint faster! Create a complete artwork on canvas in just 15 minutes. Any subject, any style.\n\nIndividual competition. All paints and brushes provided.\n\nVenue: B Block Lawn / Corridor Area (beside Hanging Bar)',
   date:'March 26–28, 2026',venue:'B Block Lawn / Corridor Area (beside Hanging Bar)',team:'Individual',
   contacts:[['Alok Prasad','9262794486'],['Shaikh Sabiya Kulsum','7587405602']],
   formLink:'https://docs.google.com/forms/d/12k_fScIUmaoTXap0OEOwLRA7he_qI5pzzrOper2eiZA/edit?ts=69c128e1'},

  {id:'cloth-painting',cat:'creative',catLabel:'Creative',icon:'👕',name:'Cloth Painting',
   img:'https://i.ibb.co/7xWWGSTk/cloth-painting.jpg',
   tagline:'Transform fabric into art at Vyom \'26 Cloth Painting!',
   desc:'👕 Vyom \'26 Cloth Painting Competition (RAG)\n\nUse fabric paints to create beautiful designs on cloth. Express your creativity through wearable art.\n\nIndividual. Fabric and basic materials provided.\n\nVenue: B Block Lawn / Corridor Area (beside Hanging Bar)',
   date:'March 26–28, 2026',venue:'B Block Lawn / Corridor Area (beside Hanging Bar)',team:'Individual',
   contacts:[['Dhananjay Kumar','7050137438'],['Divyansh Verma','9131026167']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSchrdql6psOykAYbd9_W7rgwRBjmXUpHvkRRQ05HT8nP8MVQw/viewform'},

  {id:'spin-sketch',cat:'creative',catLabel:'Creative',icon:'🌀',name:'Spin & Sketch',
   img:'https://i.ibb.co/kVhj011F/Spin-and-Sketch.jpg',
   tagline:'Art meets physics — Spin & Sketch at Vyom \'26!',
   desc:'🌀 Vyom \'26 Spin & Sketch (RAG)\n\nCreate patterns and art using spinning techniques — think spin art, spirograph-style creations.\n\nIndividual. Materials provided.\n\nVenue: A Block Porch Area',
   date:'March 26–28, 2026',venue:'A Block Porch Area',team:'Individual',
   contacts:[['Ritu Kumari','6206336251'],['Aman Kumar','6203633998']],
   formLink:'https://docs.google.com/forms/d/1nspPT6w4TLromo5TYBTEhtPtMP1xlegDWVxYQZECb1o/edit?ts=69c25ec7'},

  {id:'clay-o-rama',cat:'creative',catLabel:'Creative',icon:'🏺',name:'Clay-O-Rama',
   img:'https://i.ibb.co/M5N4KQV2/3D-art.jpg',
   tagline:'Sculpt your imagination at Vyom \'26 — Clay-O-Rama!',
   desc:'🏺 Vyom \'26 — Clay-O-Rama (RAG)\n\nBring your imagination to life in three dimensions. Sculpt, shape, and create a 3D artwork out of clay and cardboard.\n\nGroup of 4. Clay materials provided.\n\nVenue: SB18, SB19, SB17',
   date:'March 26–28, 2026',venue:'SB18, SB19, SB17',team:'Group of 4',
   contacts:[['Aarohi Mandal','8305223606'],['Amar Kumar','8305223606']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSf_nfiDdGrwL-VptVqeiEB0vUp3zBTTFhj0v0e8afQBlWaYcw/viewform'},

  {id:'squid-gambit-art',cat:'creative',catLabel:'Creative',icon:'🎮',name:'Squid Gambit Art',
   img:'https://i.ibb.co/0RnGw5VS/squid-gambit.jpg',
   tagline:'Red light, green light — Squid Gambit Art Challenge at Vyom \'26!',
   desc:'🎮 Vyom \'26 — Squid Gambit Art (RAG)\n\nInspired by Squid Game\'s iconic challenges! Includes Object Drawing, Millet Craft, and Texture Art Using Paper — all in timed red-light green-light format.\n\nGroup of 4. Materials provided.\n\nVenue: Chai ka Adda',
   date:'March 26–28, 2026',venue:'Chai ka Adda',team:'Group of 4',
   contacts:[['Diksha Sanodia','8839917857'],['Arman Khan','7587060383']],
   formLink:''},

  {id:'face-painting',cat:'creative',catLabel:'Creative',icon:'🎨',name:'Face Painting',
   img:'https://i.ibb.co/Xqzg7bp/face-painting.jpg',
   tagline:'Colorful creativity on a living canvas — Face Painting at Vyom \'26!',
   desc:'🎨 Vyom \'26 Neon View Live Face Painting — Persona Paint (RAG)\n\nTransform faces into works of art! Use safe, skin-friendly face paints to create stunning neon designs.\n\nIndividual painter who works on a volunteer model.\n\nVenue: B Block 1st Floor Front Gallery',
   date:'March 26–28, 2026',venue:'B Block 1st Floor Front Gallery',team:'Individual',
   contacts:[['Sagen Murmu','8102148923'],['Sana Khan','7222984463']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSfsvsvpZay9Xgy-0v2YggfbLDPwvk50zNvUJA7_08hq5YJjHw/viewform'},

  {id:'live-painting',cat:'creative',catLabel:'Creative',icon:'🖌️',name:'Live Painting',
   img:'https://i.ibb.co/0yfJQQ4G/live-painting.jpg',
   tagline:'Paint live in front of an audience at Vyom \'26 — The Real-Time Render!',
   desc:'🖌️ Vyom \'26 — Live Painting & Sketching: The Real-Time Render (RAG)\n\nPerform your art live in front of an audience. Time-limited session where you create a complete piece while people watch.\n\nIndividual. Your own materials or provided supplies.\n\nVenue: A Block Porch Area',
   date:'March 26–28, 2026',venue:'A Block Porch Area',team:'Individual',
   contacts:[['Aastha Agrawal','9202222751'],['Priyal Mandavi','9302290335']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLScPkLytn42vvdKBqRkW_Otdcte5CQNY4NGkeK4HvxDDmhWCoA/viewform'},

  {id:'reel-making',cat:'creative',catLabel:'Creative',icon:'🎬',name:'Reel Making',
   img:'https://i.ibb.co/b55nrTYG/reel-making.jpg',
   tagline:'Film, edit and post your best VYOM reel — most viral wins at Vyom \'26!',
   desc:'🎬 Vyom \'26 — The Viral Cut: Reel Making (RAG)\n\nCapture the essence of VYOM 2026 in a short-form video reel. Film it, edit it, post it.\n\nIndividual. Post on Instagram with the official hashtag.\n\nVenue: College Campus',
   date:'March 26–28, 2026',venue:'College Campus',team:'Individual',
   contacts:[['Hemant Chandrakar','6265619759'],['Harshit Chauhan','7042895508']],
   formLink:'https://docs.google.com/forms/d/1b1eECzZnEtTR97m8iZuUXPcKjIwEAAnefv8y5VrJW3M/edit?ts=69c243e8'},

  {id:'photography',cat:'creative',catLabel:'Creative',icon:'📸',name:'Photography',
   img:'https://i.ibb.co/tPb1Qysn/Snapfest.jpg',
   tagline:'Capture the soul of Vyom \'26 through your lens — SNAPFEST!',
   desc:'📸 Vyom \'26 SNAPFEST Photography Competition (RAG)\n\nSubmit your best shots from the VYOM 2026 festival. Submit your best 3 photos digitally.\n\nJudged on composition, storytelling and technical quality.\n\nVenue: College Campus & Film Set (FA01)',
   date:'March 26–28, 2026',venue:'College Campus & Film Set (FA01)',team:'Individual',
   contacts:[['Anshika R','9302040396'],['Ashhab Amanullah','9301579815']],
   formLink:'https://docs.google.com/forms/d/1uUm_dd6YZP_ZXezhwiLyrLXzI85jjY1vghWojxhXyf4/edit?ts=69c1076a'},

  {id:'graffiti-wall',cat:'creative',catLabel:'Creative',icon:'🖊️',name:'Graffiti Wall',
   img:'https://i.ibb.co/ZRJ5d7P4/graffiti-wall.jpg',
   tagline:'Express your art on the wall — Graffiti Wall at Vyom \'26 (COPE)!',
   desc:'🖊️ Vyom \'26 — Graffiti Wall (COPE)\n\nLet your creativity run wild on a designated wall. Spray paint, sketch, or stencil — create your masterpiece for all to see.\n\nIndividual. Materials may be provided.\n\nVenue: B Block (Corner in front of Dr. D.N. Dewangan\'s cabin)',
   date:'March 26–28, 2026',venue:'B Block (Corner in front of Dr. D.N. Dewangan\'s cabin)',team:'Individual',
   contacts:[['Aditi Ray','9123139785'],['Palak Kumari','8709029972']],
   formLink:''},

  {id:'back-to-back-drawing',cat:'creative',catLabel:'Creative',icon:'✏️',name:'Back to Back Drawing',
   img:'https://i.ibb.co/svjHPZTk/back-to-back-drawing.jpg',
   tagline:'Describe it without looking — Back to Back Drawing at Vyom \'26 (Carpediem)!',
   desc:'✏️ Vyom \'26 — Back to Back Drawing (Carpediem)\n\nSit back to back with your partner. One person describes an image, the other draws it without seeing it.\n\nPair event. Multiple rounds.\n\nVenue: A Block Porch',
   date:'March 26–28, 2026',venue:'A Block Porch',team:'Pair (2 Members)',
   contacts:[['Prerna Verma','7898398783'],['Shobhit Padhi','7489330711']],
   formLink:'https://docs.google.com/forms/d/1PLlQOKc5NIr1o7xSJ4u8_lQjD0Mqnjz83_I3Z0h8ENE/edit?ts=69c00d8e'},

  {id:'digital-magazine',cat:'creative',catLabel:'Creative',icon:'📰',name:'Digital Magazine Launch',
   img:'',
   tagline:'Design, publish and launch your very own digital magazine at Vyom \'26!',
   desc:'📰 Vyom \'26 — Digital Magazine Launch (BEACON)\n\nConceive, design and present a fully digital magazine in one creative session. Cover everything from layout and typography to content curation and visual storytelling.\n\nIndividual or team. Judged on design quality, content originality, and overall presentation.\n\nVenue: Main College Event Stage',
   date:'March 29, 2026',venue:'Main College Event Stage',team:'Individual / Team',
   contacts:[['Anshika Kumari','6206581452'],['Ishant Kumar','9142143412']],
   formLink:''},

  // ── FUN EVENTS ──
  {id:'tug-of-war',cat:'fun',catLabel:'Fun Events',icon:'🪢',name:'Tug of War',
   img:'https://i.ibb.co/KPG4196/Tug-of-war.jpg',
   tagline:'Pure team strength at Vyom \'26 Tug of War — pull your way to victory!',
   desc:'🪢 Vyom \'26 Tug of War\n\nAssemble your strongest team and pull your way to victory! The most classic test of collective strength.\n\nTeam event. Knockout format. Standard Tug of War rules.\n\nVenue: B Block Lawn',
   date:'March 26–28, 2026',venue:'B Block Lawn',team:'Team Event',
   contacts:[['Raghav Jha','8294642105'],['Gautam Kumar Singh','9931577966']],
   formLink:'https://forms.gle/Q5UhYhcnQAdpSkHeA'},

  {id:'hopscotch',cat:'fun',catLabel:'Fun Events',icon:'🎪',name:'Hopscotch (with Brick)',
   img:'https://i.ibb.co/39RF9pNR/Hopstcotch.jpg',
   tagline:'Childhood fun with a twist — Hopscotch with Bricks at Vyom \'26!',
   desc:'🎪 Vyom \'26 Hopscotch Challenge (With Bricks)\n\nRemember hopscotch from school? Now it\'s a competitive event! Navigate the brick hopscotch course as fast as possible.\n\nIndividual. Multiple rounds. Timed format.\n\nVenue: B Block Centre',
   date:'March 26–28, 2026',venue:'B Block Centre',team:'Individual',
   contacts:[['Rahul Ranjan','8603686090'],['Sahil Raja','9572765391']],
   formLink:'https://docs.google.com/forms/d/10psqRpv753xEG2TUdWme_ft9czB0nqCdJf7pJSr9XoA/edit?ts=69c18026'},

  {id:'pushup',cat:'fun',catLabel:'Fun Events',icon:'💪',name:'Push-up Competition',
   img:'https://i.ibb.co/dwMcg6dy/Push-up.jpg',
   tagline:'How many can you do? Push-up Competition at Vyom \'26!',
   desc:'💪 Vyom \'26 Push-up Competition\n\nThe player with the most proper-form push-ups wins! No breaks allowed, steady rhythm required.\n\nIndividual. Separate categories for Boys and Girls.\n\nVenue: B Block Lawn',
   date:'March 26–28, 2026',venue:'B Block Lawn',team:'Individual',
   contacts:[],
   formLink:'https://forms.gle/is1Nz81aZDSrUvDD9'},

  {id:'bar-hanging',cat:'fun',catLabel:'Fun Events',icon:'🏋️',name:'Bar Hanging Competition',
   img:'https://i.ibb.co/gZXZMcZs/Bar-Hanging.jpg',
   tagline:'Grip, endure, outlast — Bar Hanging Competition at Vyom \'26!',
   desc:'🏋️ Vyom \'26 Bar Hanging Competition\n\nHold on to the bar for as long as you can. The last one hanging wins. A pure test of grip strength and mental endurance!\n\nIndividual. No gloves permitted.\n\nVenue: B Block Centre',
   date:'March 26–28, 2026',venue:'B Block Centre',team:'Individual',
   contacts:[['Abhishek','9471623974']],
   formLink:'https://docs.google.com/forms/u/2/d/1nIRzHYu7nnUroWSzMfhj8kizPgNmAnVXiK01VRUGWBo/edit?usp=sharing_eil_se_dm&ts=69c17e84'},

  {id:'punching-demons',cat:'fun',catLabel:'Fun Events',icon:'🥊',name:'Punching Your Demons',
   img:'https://i.ibb.co/9kWvfMSz/punch-your-demons.jpg',
   tagline:'Face your fears and punch them out at Vyom \'26 — COPE!',
   desc:'🥊 Vyom \'26 — Punching Your Demons (COPE)\n\nA cathartic fun event where you quite literally punch your fears, stress, and negativity away!\n\nIndividual. Multiple rounds of punching challenges.\n\nVenue: B Block 1st Floor',
   date:'March 26–28, 2026',venue:'B Block 1st Floor',team:'Individual',
   contacts:[['Raj Narayan Singh','8102848776'],['Vaibhavi Shrivastava','8109155550']],
   formLink:'https://docs.google.com/forms/d/1tlwKFvvxKMe11zaIMHBOvMb9LlHXgAiF3PHl0z5w3y4/edit?ts=69c029f2'},

  {id:'quiz',cat:'fun',catLabel:'Fun Events',icon:'🧠',name:'Quiz (Carpediem)',
   img:'https://i.ibb.co/KzVZHZ6t/Quiz.jpg',
   tagline:'Test your knowledge across every domain at the Vyom \'26 Quiz!',
   desc:'🧠 Vyom \'26 — Quiz (Carpediem)\n\nA multi-round quiz covering general knowledge, current affairs, science, sports, entertainment and more.\n\nIndividual or team of 2. Multiple elimination rounds. Buzzer-based finals.\n\nVenue: TA18, TA19',
   date:'March 26–28, 2026',venue:'TA18, TA19',team:'Individual / Pair',
   contacts:[['Sneha Kumari','7223014442'],['Aditi Kumari','9341443846']],
   formLink:'https://docs.google.com/forms/d/1z-iTIOQiPlCel2t_COlncp6-zMD8XKwbQtuVrZ1VACw/edit?ts=69bffc44'},

  {id:'whisper-challenge',cat:'fun',catLabel:'Fun Events',icon:'🤫',name:'Whisper Challenge',
   img:'https://i.ibb.co/TMpwF1mT/Whisper-challenge.jpg',
   tagline:'Lip-read your way to victory at the Vyom \'26 Whisper Challenge!',
   desc:'🤫 Vyom \'26 — Whisper Challenge (Carpediem)\n\nWear the noise-cancelling headphones, watch your partner\'s lips, and guess the phrase! Hilarious misunderstandings guaranteed.\n\nPair event. Multiple rounds.\n\nVenue: A Block Porch',
   date:'March 26–28, 2026',venue:'A Block Porch',team:'Pair (2 Members)',
   contacts:[['Rahul Pandey','7897710801'],['Arnav Singh','7563031160']],
   formLink:'https://docs.google.com/forms/d/1YEAOSZ5nxdSc5xBoGE6Xc1RNvqwXn3JFm9UgB7ImotM/edit?ts=69c00db5'},

  {id:'emoji-tales',cat:'fun',catLabel:'Fun Events',icon:'😂',name:'Emoji Tales',
   img:'https://i.ibb.co/KpFBFXV9/Emoji-tales.jpg',
   tagline:'Tell a story in emojis — Emoji Tales at Vyom \'26 (Carpediem)!',
   desc:'😂 Vyom \'26 — Emoji Tales (Carpediem)\n\nCraft a story, movie plot, or phrase using only emojis — then let others decode it!\n\nIndividual. Multiple rounds of emoji encoding and decoding.\n\nVenue: A Block Porch',
   date:'March 26–28, 2026',venue:'A Block Porch',team:'Individual',
   contacts:[['Varun Rana','6203955524'],['Rahul Yadav','9755563988']],
   formLink:'https://docs.google.com/forms/d/16HaVSyR_LysUYhI7vtte2ctlbL5wxEOkHQCTwRz1vBY/edit?ts=69c00d25'},

  {id:'parallel-universe',cat:'fun',catLabel:'Fun Events',icon:'🌌',name:'Parallel Universe (SOMC)',
   img:'https://i.ibb.co/rRnC3m3g/parallel-universe.jpg',
   tagline:'Step into another reality at the Parallel Universe event — Vyom \'26!',
   desc:'🌌 Vyom \'26 — Parallel Universe (SOMC)\n\nAn immersive, creative event by SOMC where participants engage in alternate reality scenarios, debates, and creative storytelling challenges.\n\nIndividual or team. Multiple activities across two days.\n\nVenue: TA03',
   date:'March 26–27, 2026',venue:'TA03',team:'Individual / Team',
   contacts:[['Aditi Mittal','7869307080'],['Ayushman Pandit','6232090319']],
   formLink:'https://docs.google.com/forms/u/2/d/1a2CBJiReyH0l90vGjcNEkEpKXBeYdbJWKsdpEtTJiB8/edit?usp=sharing_eil_se_dm&ts=69bff8ca'},

  {id:'cpl-auction',cat:'fun',catLabel:'Fun Events',icon:'🏏',name:'CPL Auction',
   img:'https://i.ibb.co/Kp0fdTbr/cricket-premier-league.jpg',
   tagline:'Be the team owner — bid, strategize and win the CPL Auction at Vyom \'26!',
   desc:'🏏 Vyom \'26 — Cricket Premier League Auction (SOMC)\n\nA Cricket Premier League-style player auction event! Bid on players, build your dream team.\n\nIndividual team owners bidding for players. Budgets assigned.\n\nVenue: TA21, TA22',
   date:'March 26, 2026',venue:'TA21, TA22',team:'Individual (Team Owner)',
   contacts:[['Amar Kumar','6203633998'],['Fatima Anjum','7067797429']],
   formLink:'https://docs.google.com/forms/d/e/1FAIpQLSeSRidBau1_gsABeq7eYKeuwkh4iS-L8JbBLBY94WU27LMhTw/viewform'},

  // ── LITERARY (RADICTION) ──
  {id:'youth-parliament',cat:'literary',catLabel:'Literary',icon:'🏛️',name:'Youth Parliament',
   img:'https://i.ibb.co/NgDG9Y3B/youth-parliament.jpg',
   tagline:'Debate laws, represent your constituency at Vyom \'26 Youth Parliament!',
   desc:'🏛️ Vyom \'26 Youth Parliament (Radiction)\n\nExperience the world of democracy and governance. Take on roles as members of parliament, debate bills, represent constituencies.\n\nTeam/individual. Multiple sessions.\n\nVenue: RIPER Hall',
   date:'March 27, 2026',venue:'RIPER Hall',team:'Individual / Group',
   contacts:[['Vimla Choudhary','9303521298'],['Laghvensh Sahu','7999354525']],
   formLink:'https://docs.google.com/forms/u/2/d/1wea3_TRBDzCnIiQgacGjCoaKU4F4XWebdUsX98hUopU/edit?usp=sharing_eip_se_dm&ts=69bf8178'},

  {id:'debate',cat:'literary',catLabel:'Literary',icon:'💬',name:'Debate',
   img:'https://i.ibb.co/qMhwqCcH/Debate.jpg',
   tagline:'Argue, persuade, win — the Debate competition at Vyom \'26!',
   desc:'💬 Vyom \'26 Debate Competition (Radiction)\n\nStructured debate on current topics. Both sides get equal time to argue their position — the stronger argument wins.\n\nPairs or individual. Topics announced on the spot or with 15 min prep.\n\nVenue: TA01',
   date:'March 26–28, 2026',venue:'TA01',team:'Individual / Pairs',
   contacts:[['Ayush Kumar Singh','8602911654'],['Bhoomi Shrivastava','8305518552']],
   formLink:'https://docs.google.com/forms/d/1HpvI2t-7VkNFKehb0UwvK3Ue8dArFkB-1aY-aVL_BpE/edit?ts=69bf81a1'},

  {id:'extempore',cat:'literary',catLabel:'Literary',icon:'🗣️',name:'Extempore',
   img:'https://i.ibb.co/j9bBNLMj/Extempore.jpg',
   tagline:'Think on your feet and speak without preparation at Vyom \'26 Extempore!',
   desc:'🗣️ Vyom \'26 Extempore Speaking Competition (Radiction)\n\nReceive your topic just 1 minute before you speak — then deliver a confident, structured, 3-minute talk. No notes allowed.\n\nIndividual. Multiple rounds.\n\nVenue: TA02',
   date:'March 26–28, 2026',venue:'TA02',team:'Individual',
   contacts:[['Mohit Kumar Sinha','7488286743'],['Kanak Kumari','6202500000']],
   formLink:'https://docs.google.com/forms/d/1YETq3_mdbIP-uKP4Vj5RQq_ydGjQ_nU9kHxgCh5lUqQ/edit?ts=69bf81c0'},

  {id:'open-mic',cat:'literary',catLabel:'Literary',icon:'🎙️',name:'Open Mic',
   img:'https://i.ibb.co/yjv6wzj/Open-Mic.jpg',
   tagline:'Your words, your stage — Open Mic at Vyom \'26!',
   desc:'🎙️ Vyom \'26 Open Mic (Radiction)\n\nStep up to the mic and share whatever moves you — poetry, spoken word, stand-up comedy, storytelling, rap or prose.\n\nIndividual. 3–5 minute slots.\n\nVenue: Chai ka Adda',
   date:'March 26–28, 2026',venue:'Chai ka Adda',team:'Individual',
   contacts:[['Akriti Singh','9651900852'],['Sourav Kumar','9229926618']],
   formLink:'https://docs.google.com/forms/d/16s-PAxyvRhd7lhTg1PoT0RmR98mjpj8JpqH8BkHA-14/edit?ts=69bf81da'},

  {id:'un-summit',cat:'literary',catLabel:'Literary',icon:'🌐',name:'UN Summit',
   img:'https://i.ibb.co/WWtZ5c6Z/United-Nation-Summit.jpg',
   tagline:'Represent nations, debate global issues at Vyom \'26 UN Summit (Carpediem)!',
   desc:'🌐 Vyom \'26 — UN Summit (Carpediem)\n\nA Model United Nations-style event. Represent a country, debate global resolutions, and negotiate your way to a consensus.\n\nIndividual participants representing nations. Multiple committee sessions.\n\nVenue: TA18',
   date:'March 26, 2026',venue:'TA18',team:'Individual (Nation Representative)',
   contacts:[['Varun Rana','6203955524'],['Rahul Yadav','9755563988']],
   formLink:'https://docs.google.com/forms/d/1mJ3370hSJA0sg5_I-yzWTFt_6f-Ff6Z5b8AhIxRDvXE/edit?ts=69bffb7e'},

  // ── INITIATIVES ─────────────────────────────────────────────
  {id:'bring-smile-box',cat:'initiative',catLabel:'Initiative',icon:'😊',name:'Bring Smile Box',
   img:'',
   tagline:'Spread joy and kindness — contribute to the Bring Smile Box at Vyom \'26!',
   desc:'😊 Vyom \'26 — Bring Smile Box (RISE & NSS)\n\nA heartwarming community initiative where participants contribute items — stationery, books, clothes, or small gifts — to bring smiles to those in need.\n\nOpen to everyone. No competition — just compassion.\n\nVenue: Campus Collection Points',
   date:'March 26–28, 2026',venue:'Campus Collection Points',team:'Open to All',
   contacts:[],
   formLink:''},

  {id:'first-aid',cat:'initiative',catLabel:'Initiative',icon:'🩺',name:'First Aid Event',
   img:'',
   tagline:'Learn essential first aid skills at Vyom \'26 — be the help before help arrives!',
   desc:'🩺 Vyom \'26 — First Aid Event (RISE & NSS)\n\nA vital awareness and training event covering essential first aid techniques. Learn how to respond in emergencies — CPR, wound care, fracture management, and more.\n\nOpen to all students and staff. Interactive demonstrations and practice sessions.\n\nVenue: Complete College Campus',
   date:'March 26–28, 2026',venue:'Complete College Campus',team:'Open to All',
   contacts:[['Tanya Patel','9399583147'],['Fatima Mohammad','9302610881']],
   formLink:''},

  {id:'clean-campus',cat:'initiative',catLabel:'Initiative',icon:'🌿',name:'Clean Campus Drive',
   img:'',
   tagline:'Let\'s keep Rungta beautiful — join the Clean Campus Drive at Vyom \'26!',
   desc:'🌿 Vyom \'26 — Clean Campus Drive (RISE & NSS)\n\nA collective responsibility initiative where students, staff, and faculty come together to keep the campus clean and green during the festival.\n\nVolunteer for cleanliness drives, waste segregation, and eco-friendly festival practices.\n\nVenue: Complete College Campus',
   date:'March 26–28, 2026',venue:'Complete College Campus',team:'Open to All',
   contacts:[['Srishti Anand','8271908209'],['Shymali Samant','9955320967']],
   formLink:''},

];
