const PHOTOS = [
  { src:'https://i.ibb.co/zW0nsxBv/1000331782.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Campus Energy' },
  { src:'https://i.ibb.co/JwhXsvt0/1000331784.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Crowd & Culture' },
  { src:'https://i.ibb.co/JWZZPvN0/1000331792.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Moments Captured' },
  { src:'https://i.ibb.co/KBgXptW/1000331798.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Arena Vibes' },
  { src:'https://i.ibb.co/G40MxyJH/IMG-1623.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Behind the Scenes' },
  { src:'https://i.ibb.co/Y4XfGQx8/IMG-1668.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Stage Moments' },
  { src:'https://i.ibb.co/3mnwnddb/IMG-1673.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Unscripted Joy' },
  { src:'https://i.ibb.co/qMxcSPWy/IMG-1757.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Performers Spotlight' },
  { src:'https://i.ibb.co/YTTm6nvb/IMG-1860.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Game Faces' },
  { src:'https://i.ibb.co/8DJ9hQr2/IMG-2043.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Crowd Goes Wild' },
  { src:'https://i.ibb.co/20KBCkzT/IMG-2052.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Winners Circle' },
  { src:'https://i.ibb.co/6cSprD4p/IMG-3150.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Culture Day' },
  { src:'https://i.ibb.co/c78CNWp/IMG-3136.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Campus Life' },
  { src:'https://i.ibb.co/CszVZrm9/IMG-3200-1.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Festival Frames' },
  { src:'https://i.ibb.co/1ffx4WbF/IMG-20250407-WA0013.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Real Moments' },
  { src:'https://i.ibb.co/kgJS13Z3/IMG-20250407-WA0015.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Energy Levels High' },
  { src:'https://i.ibb.co/N66LPdmC/IMG-20250407-WA0017.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Squad Goals' },
  { src:'https://i.ibb.co/Gf7Qzcrk/IMG-20250407-WA0020.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Together We Rise' },
  { src:'https://i.ibb.co/rGLGdDLR/IMG20250326162130.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Afternoon Sessions' },
  { src:'https://i.ibb.co/1GhqPBFx/IMG20250407110821.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Morning of the Game' },
  { src:'https://i.ibb.co/fdPkbPZC/FVD-9623-1.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Professional Capture' },
  { src:'https://i.ibb.co/JF23XgSr/FVD-9539.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — In Frame' },
  { src:'https://i.ibb.co/j9tvCdc7/FVD-9529.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Festival Light' },
  { src:'https://i.ibb.co/j9LbMW2N/FVD-9521.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Peak Hours' },
  { src:'https://i.ibb.co/GvBTdT27/FVD-9351.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Candid Shots' },
  { src:'https://i.ibb.co/pv77PLHm/FVD-9346.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Performance Still' },
  { src:'https://i.ibb.co/39NmvjNv/FVD-9345.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Stage to Screen' },
  { src:'https://i.ibb.co/hRS1LCrV/FVD-9343-1.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Studio Frames' },
  { src:'https://i.ibb.co/Dfqkxps4/FVD-9344.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Captured Glory' },
  { src:'https://i.ibb.co/Vpg2gTyS/DSC00040.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — DSLR Chronicles' },
  { src:'https://i.ibb.co/MyhFsSN3/DSC00036.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — The Arena' },
  { src:'https://i.ibb.co/fz4NHByw/DSC00028.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Wide Shot' },
  { src:'https://i.ibb.co/6J178SXm/DSC00014.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Opening Day' },
  { src:'https://i.ibb.co/NnWsQT9r/DSC-8619.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Full House' },
  { src:'https://i.ibb.co/DH7vKdT0/DSC-8552.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Action Freeze' },
  { src:'https://i.ibb.co/MyPPt2pj/DSC-8551.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Moment in Motion' },
  { src:'https://i.ibb.co/m5gsnTb2/DSC-8545.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Lens Stories' },
  { src:'https://i.ibb.co/LhqvqF89/DSC-8362.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Campus Frame' },
  { src:'https://i.ibb.co/MkbfzdCy/DSC-8317.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — The Crowd' },
  { src:'https://i.ibb.co/F42Zwd5N/DSC-8307.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Fest Frames' },
  { src:'https://i.ibb.co/4wg9CGT9/DSC-8306.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Side Stage' },
  { src:'https://i.ibb.co/jkG28LCV/DSC-8298.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Night Lights' },
  { src:'https://i.ibb.co/MxY2CVDJ/DSC-8269.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Stage Glow' },
  { src:'https://i.ibb.co/B5HgsNJD/DSC-8231-1.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Stars of the Show' },
  { src:'https://i.ibb.co/8Z9TdZY/DSC-8218.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Electric Atmosphere' },
  { src:'https://i.ibb.co/Gg42kLY/DSC-8141.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Colour & Light' },
  { src:'https://i.ibb.co/JW5Z1fyC/DSC-8128.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Behind the Lens' },
  { src:'https://i.ibb.co/0jz0QSLx/DSC-8090.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Raw Energy' },
  { src:'https://i.ibb.co/yn1sSh2q/DSC-8082.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Real & Unfiltered' },
  { src:'https://i.ibb.co/xS2VSYRX/DSC-8054.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Golden Hours' },
  { src:'https://i.ibb.co/HfBTBn9Z/DSC-8036.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Story of a Fest' },
  { src:'https://i.ibb.co/vCFQyShh/DSC-8023.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Every Frame Counts' },
  { src:'https://i.ibb.co/60MNTCKZ/DSC-7954.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — The Day Unfolds' },
  { src:'https://i.ibb.co/F4LY7YxP/DSC-7950.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Laughter & Life' },
  { src:'https://i.ibb.co/fzPz9xJk/DSC-7939.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Fest Diary' },
  { src:'https://i.ibb.co/845hCYPP/DSC-7910.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Rungta Remembers' },
  { src:'https://i.ibb.co/nGzwjHX/DSC-7902.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — Last Day Feels' },
  { src:'https://i.ibb.co/bjhXhnJc/DSC-7817.jpg', cat:'highlights', tag:'Highlights', cap:'Vidyut — End Credits Roll' },
  { src:'https://i.ibb.co/vx97T1ZB/White-Modern-Mothers-Day-Presentation-43.jpg', cat:'highlights', tag:'Highlights', cap:'Rungta University — Campus' },
];
